### ISSUE TITLE
Yotpo compatible version

### ISSUE THREAD

**Issue by amit-parmar-7** [YotpoLtd/salesforce-cartridge#17]
Hi, 

Is Yotpo's latest cartridge version supported with SFRA version 7.0.0 and compatibility 22.7 ? quick response will be very helpful.

Thanks,

**Comment by WarriorAchilles** [comment]
Apologies for the delay here.

The cartridge has not been thoroughly tested with SFRA 7 and compatibility 22.7. Some upgrades to the cartridge have been made recently addressing some issues found with newer compatibility modes in an effort to ensure the cartridge works across most compatibility modes, but a thorough test to confirm support for SFRA 7 and compatibility 22.7 has not been conducted.
